version: '3.7'

networks:
  assignment:
    driver: bridge

services:
  webappphp:
    build:
      context: ../
      dockerfile: cd/webapp/php/Dockerfile
    container_name: assignment-webapp-php
    networks:
      - assignment
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ../
        target: /var/www/assignment/
        read_only: false
    working_dir: /var/www/assignment
    restart: unless-stopped
  webappmysql:
    image: mysql:5.7
    container_name: assignment-webapp-mysql
    networks:
      - assignment
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: assignment
      MYSQL_ROOT_PASSWORD: Pas5w0rd
      MYSQL_PASSWORD: Pas5w0rd
      MYSQL_USER: assignment
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # volumes:
    #   - ./mysql/my.cnf:/etc/mysql/my.cnf
    #   - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
  redis:
    build:
      context: ../
      dockerfile: cd/redis/Dockerfile
    container_name: assignment-redis
    networks:
      - assignment
    ports:
      - "6379:6379/tcp"
    hostname: redis
    restart: unless-stopped
