version: '3.7'

networks:
  assignment:
    driver: bridge

services:
  php:
    build:
      context: ../
      dockerfile: cd/php/Dockerfile
    container_name: assignment-php
    networks:
      - assignment
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ../
        target: /var/www/assignment/
        read_only: false
    working_dir: /var/www/assignment
    restart: unless-stopped
